#!/bin/sh

tshark -i eth0 -T fields -f "udp" -e ip.dst -Y "ip.dst!=192.168.0.0/16 and ip.dst!=10.0.0.0/8 and ip.dst!=172.16.0.0/12" -c 100 |sort -u |xargs|sed "s/ / and ip.dst!=/g" |sed "s/^/ip.dst!=/g"

echo "Press Enter and call your target."

read line

while read -r line; do 
        whois "$line" > /tmp/b
        
tshark -i eth0 -l -T fields -f "udp" -e ip.dst -Y "$filter" -Y "ip.dst!=192.168.0.0/16 and ip.dst!=10.0.0.0/8 and ip.dst!=172.16.0.0/12"

        filter=$(cat /tmp/b |xargs| grep -E -iv "facebook|google"|wc -c)

        if [ "$filter" -gt 0 ];
        then targetinfo=$(cat /tmp/b| grep -E -iw "OrgName:|NetName:|Country:")
echo "$line" --- "$targetinfo"
        fi
done
